
'use client';

import type { BrandKitOutput } from '@/ai/flows/generate-brand-kit-from-input';
import Image from 'next/image';
import { AppLogo } from './app-logo';
import { Badge } from './ui/badge';

interface BrandKitPdfLayoutProps {
  brandKit: BrandKitOutput;
  logoDataUri?: string;
}

export function BrandKitPdfLayout({ brandKit, logoDataUri }: BrandKitPdfLayoutProps) {
  return (
    <div className="bg-white text-slate-900 p-16 font-sans">
      <header className="flex justify-between items-center pb-8 border-b-2 border-slate-200">
        <div>
          <h1 className="text-5xl font-bold tracking-tighter">Brand Kit</h1>
          <p className="text-xl text-slate-500 mt-2">Generated by Brand Vision In Seconds</p>
        </div>
        <AppLogo />
      </header>

      <main className="mt-12 grid grid-cols-3 gap-12 items-start">
        {/* Left Column */}
        <div className="col-span-1 space-y-12">
          {logoDataUri && (
            <div className="p-8 bg-slate-100 rounded-2xl flex items-center justify-center">
              <Image
                src={logoDataUri}
                alt="Uploaded Logo"
                width={200}
                height={200}
                className="object-contain max-h-48"
              />
            </div>
          )}
          
          <div>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">Color Palette</h2>
            <div className="grid grid-cols-2 gap-4">
              {Object.entries(brandKit.colorPalette).map(([name, color]) => (
                <div key={name} className="p-4 rounded-lg border border-slate-200">
                  <div
                    className="w-full h-16 rounded-md mb-2"
                    style={{ backgroundColor: color }}
                  />
                  <div className="text-sm font-semibold capitalize text-slate-800">{name}</div>
                  <div className="text-xs text-slate-500 font-mono">{color}</div>
                </div>
              ))}
            </div>
          </div>

          <div>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">Typography</h2>
            <div className="mt-4 space-y-4">
              {Object.entries(brandKit.typographySuggestions).map(([type, font]) => (
                <div key={type} className="p-4 bg-slate-50 rounded-lg">
                  <div className="text-sm capitalize text-slate-500">{type}</div>
                  <div className="text-2xl font-semibold mt-1 text-slate-900">{font}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column */}
        <div className="col-span-2 space-y-12">
           <div>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">Recommended Platforms</h2>
            <div className="mt-4 space-y-4">
              {brandKit.recommendedPlatforms.map((platform) => (
                <div
                  key={platform.name}
                  className={`p-6 rounded-xl ${
                    platform.bestChoice
                      ? 'bg-blue-600 text-white'
                      : 'bg-slate-50 text-slate-800'
                  }`}
                >
                   <div className="flex justify-between items-start">
                      <h3 className="text-2xl font-bold">{platform.name}</h3>
                      <Badge
                         className={platform.bestChoice
                          ? 'bg-white/20 text-white'
                          : 'bg-slate-200 text-slate-600'}
                      >
                        {platform.bestChoice ? 'Best Choice' : 'Alternative'}
                      </Badge>
                    </div>
                  <p className={`mt-2 ${platform.bestChoice ? 'text-blue-100' : 'text-slate-600'}`}>
                    {platform.description}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {brandKit.siteStructure && brandKit.siteStructure.length > 0 && (
              <div>
                  <h2 className="text-2xl font-bold text-slate-800 mb-4">Site Structure</h2>
                  <div className="mt-4 grid grid-cols-2 gap-x-8 gap-y-6">
                      {brandKit.siteStructure.map((page, index) => (
                          <div key={index}>
                              <h3 className="text-lg font-semibold border-b pb-2 mb-3 text-slate-800">{page.page}</h3>
                              <ul className="mt-2 space-y-1 list-disc list-inside text-slate-600">
                              {page.sections.map((section, sIndex) => (
                                  <li key={sIndex}>{section}</li>
                              ))}
                              </ul>
                          </div>
                      ))}
                  </div>
              </div>
          )}

          <div>
            <h2 className="text-2xl font-bold text-slate-800 mb-4">Competitor Websites</h2>
            <ul className="mt-4 space-y-2">
              {brandKit.competitorWebsites.map((url, index) => (
                <li key={index} className="flex items-center gap-3 group">
                    <span className="text-sm font-medium text-slate-700 hover:underline">
                        {url.replace(/^www\./, '')}
                    </span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
}
